export const People = [
    {
        id: 0,
        name: "Ai-Lee-Woods",

    },
    {
        id: 1,
        name: "Anna-Monaghan",
    },
    {
        id: 2,
        name: "Declan-OConnell",
    },
    {
        id: 3,
        name: "Elana-Sheinkopf",
    },
    {
        id: 4,
        name: "Erica-Erdenesanaa",
    },
    {
        id: 5,
        name: "Gwen-Gleason",
    },
    {
        id: 6,
        name: "Martina-Tognato-Guaqueta",
    },
    {
        id: 7,
        name: "Mira-Pickus",
    },
    {
        id: 8,
        name: "Molly-Richardson",
    },
    {
        id: 9,
        name: "Rain-Jocas",
        workName: "Restaurant Worker",
        workClothingimg: "",
        workClothingimgAlt: "alt text",
        workClothingPeiceList: "",
        musicName: "Gustav Holst's the Planets",
        musicStatement: "",
        musicimg1: "",
        musicimg1Alt: "alt text",
        musicimg2: "",
        musicimg2Alt: "alt text",
        musicPeiceList: "",
        constructionName: "Batman Unburied",
        constructionStatement: "The chosen piece is the first episode of the podcast Batman Unburied. It takes place almost entirely in Bruce Wayne (Batman’s) own mind. This disconnect from reality is demonstrated by the valueizing color designs of old black and white films, invoking the black and white origins of the characters in comics. The color effects and character designs also invoke one of the most important characteristics of Batman comics and their history- camp. Character costumes within Bruce’s mind are more a reflection of Bruce’s perception of them than of their own characters, and invoke bat elements as a reference to his psyche. Although bruce himself is acting as a doctor, he  is dressed in elements of the Batman suit, like a kid playing dress up. After all, this is nothing but a fantasy. Characters outside of Bruce’s mind, like Barbara Gordon (Batgirl)  use colors closer to the norm, which helps to clue in the audience that what is happening is not reality.",
        constructionimg1: "",
        constructionimg1Alt: "alt text",
        constructionimg2: "",
        constructionimg2Alt: "alt text",
        constructionimg3: "",
        constructionimg3Alt: "alt text",
        finalName: "",
        finalStatement: "Although England has its own folklore surrounding fairies, Shakespeare’s fairies share more commonalities with those from Welsh folklore.  There are many different colors ascribed to faeries in Welsh folklore, depending on the type of faerie, and the region of the myth. For example the “the old elves of the blue petticoat”, the “Green Lady of Caerphilly” who is a goblin character, and the fairies of Frennifawr who dressed in red. However the most common color for faeries in welsh folklore seems to be white. Blue, green, red, and especially white will be the colors of the fairies. In particular, Puck will be dressed in green like the Green Lady of Caerphilly and Titania will be dressed in many layers of white. Stories about fairies in particular often place them as gone but very recent past. However, the age of fairies is typically placed around the same time as the Arthurian legends, which are said to have occured in the 5th-6th century. Because of this, I will be placing the fairies in 5th century Celtic dress. Additionally folklore inherently has a sense of timelessness, so I would like to place the mortals in the 15th-17th century, as a point of contrast against the fairies.",
        finalimg1: "",
        finalimg1Alt: "alt text",
        finalimg2: "",
        finalimg2Alt: "alt text",
        finalimg3: "",
        finalimg3Alt: "alt text",
        finalimg4: "",
        finalimg4Alt: "alt text",
        finalimg5: "",
        finalimg5Alt: "alt text",
    },
    {
        id: 10,
        name: "Space-Pace",
        workName: "",
        workClothingimg: "",
        workClothingimgAlt: "",
        workClothingPeiceList: "",
        musicName: "",
        musicStatement: "",
        musicimg1: "",
        musicimg1Alt: "",
        musicimg2: "",
        musicimg2Alt: "",
        musicPeiceList: "",
        constructionName: "",
        constructionStatement: "",
        constructionimg1: "",
        constructionimg1Alt: "",
        constructionimg2: "",
        constructionimg2Alt: "",
        constructionimg3: "",
        constructionimg3Alt: "",
        finalName: "",
        finalStatement: "",
        finalimg1: "",
        finalimg1Alt: "",
        finalimg2: "",
        finalimg2Alt: "",
        finalimg3: "",
        finalimg3Alt: "",
        finalimg4: "",
        finalimg4Alt: "",
        finalimg5: "",
        finalimg5Alt: "",
    },
    {
        id: 11,
        name: "Tali-Serlin",
    },
    {
        id: 12,
        name: "Zoe-Buettner",
    },

]