/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        skyBlue: "#8ED1FC",
        paleBlue: "#E6F2F9",
        lightBlue: "#D7ECFA",
        theme_blue: "#0471A6",
        blueGrey: "#577588",
        darkBlue: "#5242FF",
        blueBlack: "#001824",
        purple: "#4E598C",
        lightGray: "#F5F5F5",
        darkGray: "#0005",
        theme_red: "#E15554",
        orange: "#F18F01",
        jasper:  "#CD533B",
        cinebar: "#E25F44",
        darkRed: "#D62839",
        lightPurple: "#B8B8F3",
        violet: "#A4209A",
        indigo: "#9989FF",
        magenta: "#B57BA6",
        darkPurple: "#2E294E",
        theme_pink: "#EF8FFF",
        palePurple: "#FBF1FB",
        blue: "blue",
        offWhite: "#EAFFF0",
        lightGreen: "#CFFFDC",
        jade: "#39AA68",
        green: "#2E6F40",
        darkGreen: "#253D2C",
        pine: "#1A7260",
      },
    },
  },
  plugins: [],
};
